In [1]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv('pii_dataset.csv')
df.head()

,document,text,tokens,trailing_whitespace,labels,prompt,prompt_id,name,email,phone,job,address,username,url,hobby,len
0,1073d46f-2241-459b-ab01-851be8d26436,"My name is Aaliyah Popova, and I am a jeweler ...","['My', 'name', 'is', 'Aaliyah', 'Popova,', 'an...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Aaliyah Popova is a jeweler with 13 year...,1,Aaliyah Popova,aaliyah.popova4783@aol.edu,(95) 94215-7906,jeweler,97 Lincoln Street,NaN,NaN,Podcasting,363.0
1,5ec717a9-17ee-48cd-9d76-30ae256c9354,"My name is Konstantin Becker, and I'm a develo...","['My', 'name', 'is', 'Konstantin', 'Becker,', ...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Konstantin Becker is a developer with 2 ...,1,Konstantin Becker,konstantin.becker@gmail.com,0475 4429797,developer,826 Webster Street,NaN,NaN,Quilting,255.0
2,353da41e-7799-4071-ab20-d959b362612e,"As Mieko Mitsubishi, an account manager at a p...","['As', 'Mieko', 'Mitsubishi,', 'an', 'account'...","[True, True, True, True, True, True, True, Tru...","['O', 'B-NAME_STUDENT', 'I-NAME_STUDENT', 'O',...",\n Mieko Mitsubishi is a account manager. W...,3,Mieko Mitsubishi,mieko_mitsubishi@msn.org,+27 61 222 4762,account manager,1309 Southwest 71st Terrace,NaN,NaN,Metal detecting,259.0
3,9324ee01-7bdc-41b1-a7a5-01307f72c20d,"My name is Kazuo Sun, and I'm an air traffic c...","['My', 'name', 'is', 'Kazuo', 'Sun,', 'and', ""...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Kazuo Sun is a air traffic controller wi...,1,Kazuo Sun,kazuosun@hotmail.net,0304 2215930,air traffic controller,736 Sicard Street Southeast,NaN,NaN,Amateur radio,281.0
4,971fe266-2739-4f1b-979b-7f64e07d5a4a,"My name is Arina Sun, and I'm a dental hygieni...","['My', 'name', 'is', 'Arina', 'Sun,', 'and', ""...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Arina Sun is a dental hygienist. Write a...,3,Arina Sun,arina-sun@gmail.net,0412 1245924,dental hygienist,5701 North 67th Avenue,NaN,NaN,Related,210.0

In [12]:
df.drop('tokens', axis=1)

,document,text,trailing_whitespace,labels,prompt,prompt_id,name,email,phone,job,address,username,url,hobby,len
0,1073d46f-2241-459b-ab01-851be8d26436,"My name is Aaliyah Popova, and I am a jeweler ...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Aaliyah Popova is a jeweler with 13 year...,1,Aaliyah Popova,aaliyah.popova4783@aol.edu,(95) 94215-7906,jeweler,97 Lincoln Street,NaN,NaN,Podcasting,363.0
1,5ec717a9-17ee-48cd-9d76-30ae256c9354,"My name is Konstantin Becker, and I'm a develo...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Konstantin Becker is a developer with 2 ...,1,Konstantin Becker,konstantin.becker@gmail.com,0475 4429797,developer,826 Webster Street,NaN,NaN,Quilting,255.0
2,353da41e-7799-4071-ab20-d959b362612e,"As Mieko Mitsubishi, an account manager at a p...","[True, True, True, True, True, True, True, Tru...","['O', 'B-NAME_STUDENT', 'I-NAME_STUDENT', 'O',...",\n Mieko Mitsubishi is a account manager. W...,3,Mieko Mitsubishi,mieko_mitsubishi@msn.org,+27 61 222 4762,account manager,1309 Southwest 71st Terrace,NaN,NaN,Metal detecting,259.0
3,9324ee01-7bdc-41b1-a7a5-01307f72c20d,"My name is Kazuo Sun, and I'm an air traffic c...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Kazuo Sun is a air traffic controller wi...,1,Kazuo Sun,kazuosun@hotmail.net,0304 2215930,air traffic controller,736 Sicard Street Southeast,NaN,NaN,Amateur radio,281.0
4,971fe266-2739-4f1b-979b-7f64e07d5a4a,"My name is Arina Sun, and I'm a dental hygieni...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Arina Sun is a dental hygienist. Write a...,3,Arina Sun,arina-sun@gmail.net,0412 1245924,dental hygienist,5701 North 67th Avenue,NaN,NaN,Related,210.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,377128b4-e7d5-492a-93a4-3d6e0fe8d671,"In the tapestry of life, I, Shankar Koch, am b...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'O', 'O', 'O', 'B-NAME_STUDENT...",\n Write a fictional semi-formal biography ...,0,Shankar Koch,shankar.koch@msn.org,(83) 91541-5670,communicator,22352 North 67th Drive,NaN,NaN,Juggling,478.0
3416,e40dd02a-3e8d-4455-9ac5-e4fd74f8a1b9,"Arina Suzuki, a highly skilled translator with...","[True, True, True, True, True, True, True, Tru...","['B-NAME_STUDENT', 'I-NAME_STUDENT', 'O', 'O',...",\n Arina Suzuki is a translator. Write abou...,2,Arina Suzuki,arina.suzuki@outlook.net,(81) 91579-9309,translator,19237 North 69th Avenue,NaN,NaN,Movie reviews,239.0
3417,38114e49-1bc3-4157-981b-15535e3b7778,In my role as a dental hygienist with one year...,"[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",\n Yoshie Schneider is a dental hygienist w...,1,Yoshie Schneider,yoshieschneider@outlook.org,(525) 749-1703,dental hygienist,678 Fairlane Street,NaN,NaN,Remote cars,352.0
3418,47b71560-20d8-47a3-b518-34a186c3fb02,"Masahiro Rodriguez, a seasoned salesperson wit...","[True, True, True, True, True, True, True, Tru...","['B-NAME_STUDENT', 'I-NAME_STUDENT', 'O', 'O',...",\n Masahiro Rodriguez is a salesperson. Wri...,2,Masahiro Rodriguez,masahiro.rodriguez@aol.org,0955 1929331,salesperson,1217 Southwest 91st Street,NaN,NaN,Poetry,313.0
3419,e13a3ec3-ef02-410c-ae9c-7c2d1ef2484f,In my role as a chef with over 9 years of expe...,"[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",\n Leo Weber is a chef with 9 years of expe...,5,Leo Weber,leoweber2902@h,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
sentence_df=df['text']
sentence_df.head()

0    My name is Aaliyah Popova, and I am a jeweler ...
1    My name is Konstantin Becker, and I'm a develo...
2    As Mieko Mitsubishi, an account manager at a p...
3    My name is Kazuo Sun, and I'm an air traffic c...
4    My name is Arina Sun, and I'm a dental hygieni...
Name: text, dtype: object

In [14]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

df['tokens']=df['text'].apply(lambda a: tokenizer.tokenize(str(a), truncation=True))
pd.set_option('display.max_colwidth', None)
df['tokens'].head()

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

0                                                                                                 [▁My, ▁name, ▁is, ▁A, al, iyah, ▁Pop, ova, ,, ▁and, ▁I, ▁am, ▁a, ▁je, wel, er, ▁with, ▁13, ▁years, ▁of, ▁experience, ., ▁I, ▁remember, ▁a, ▁very, ▁unique, ▁and, ▁challenging, ▁project, ▁I, ▁had, ▁to, ▁work, ▁on, ▁last, ▁year, ., ▁A, ▁customer, ▁approach, ed, ▁me, ▁with, ▁a, ▁precio, us, ▁family, ▁, heir, loom, ▁-, ▁a, ▁dia, mond, ▁nec, kla, ce, ▁that, ▁had, ▁been, ▁passed, ▁down, ▁through, ▁generation, s, ., ▁Unfortunately, ,, ▁the, ▁nec, kla, ce, ▁was, ▁in, ▁poor, ▁condition, ,, ▁with, ▁several, ▁loo, se, ▁dia, mond, s, ▁and, ▁a, ▁broken, ▁cla, sp, ., ▁The, ▁customer, ▁wanted, ▁me, ▁to, ▁resto, re, ▁it, ▁to, ...]
1    [▁My, ▁name, ▁is, ▁Konstantin, ▁Beck, er, ,, ▁and, ▁I, ', m, ▁a, ▁developer, ▁with, ▁two, ▁years, ▁of, ▁experience, ., ▁I, ▁recently, ▁worked, ▁on, ▁a, ▁project, ▁where, ▁we, ▁built, ▁a, ▁new, ▁customer, ▁portal, ▁for, ▁our, ▁company, ., ▁The, ▁goal, ▁was, ▁to, ▁create, ▁a, ▁more, ▁user, -, friendly, ▁and, ▁intuitiv, e, ▁interface, ▁that, ▁would, ▁make, ▁it, ▁easier, ▁for, ▁customers, ▁to, ▁manage, ▁their, ▁account, s, ▁and, ▁access, ▁information, ., ▁We, ▁started, ▁by, ▁ga, ther, ing, ▁requirements, ▁from, ▁our, ▁customers, ▁and, ▁conduct, ing, ▁user, ▁research, ▁to, ▁understand, ▁their, ▁needs, ▁and, ▁pain, ▁points, ., ▁We, ▁then, ▁designed, ▁a, ▁new, ▁user, ▁interface, ▁that, ▁was, ▁both, ▁visual, ...]
2                                                   [▁As, ▁Mi, eko, ▁Mitsubishi, ,, ▁an, ▁account, ▁manager, ▁at, ▁a, ▁prominent, ▁software, ▁company, ,, ▁I, ▁encounter, ed, ▁a, ▁unique, ▁challenge, ▁that, ▁required, ▁my, ▁ut, mos, t, ▁dedicati, on, ▁and, ▁expertise, ▁to, ▁solve, ., ▁The, ▁issue, ▁a, rose, ▁when, ▁one, ▁of, ▁our, ▁value, d, ▁clients, ,, ▁a, ▁leading, ▁multi, national, ▁corporation, ,, ▁reported, ▁in, cons, isten, cies, ▁in, ▁their, ▁data, ▁, analytic, s, ▁platform, ., ▁The, ▁disc, re, pa, ncies, ▁were, ▁affect, ing, ▁their, ▁decision, -, making, ▁process, es, ▁and, ▁causing, ▁un, certa, in, ty, ▁within, ▁their, ▁operation, s, ., ▁With, ▁a, ▁sense, ▁of, ▁urge, ncy, ,, ▁I, ▁del, ved, ▁into, ...]
3                                                                                   [▁My, ▁name, ▁is, ▁Kaz, u, o, ▁Sun, ,, ▁and, ▁I, ', m, ▁an, ▁air, ▁traffic, ▁controller, ▁with, ▁seven, ▁years, ▁of, ▁experience, ., ▁I, ', ve, ▁always, ▁been, ▁fascina, ted, ▁by, ▁avia, tion, ,, ▁and, ▁I, ▁love, ▁the, ▁challenge, ▁of, ▁keeping, ▁planes, ▁safe, ▁and, ▁on, ▁time, ., ▁One, ▁of, ▁the, ▁most, ▁memor, able, ▁projects, ▁I, ▁worked, ▁on, ▁was, ▁a, ▁major, ▁upgrade, ▁to, ▁our, ▁airport, ', s, ▁radar, ▁system, ., ▁The, ▁old, ▁system, ▁was, ▁out, da, ted, ▁and, ▁pro, ne, ▁to, ▁break, down, s, ,, ▁and, ▁it, ▁was, ▁becoming, ▁increasing, ly, ▁difficult, ▁to, ▁keep, ▁up, ▁with, ▁the, ▁growing, ▁number, ▁of, ▁flight, s, ...]
4                                                                                                   [▁My, ▁name, ▁is, ▁Ar, ina, ▁Sun, ,, ▁and, ▁I, ', m, ▁a, ▁dental, ▁hygien, ist, ., ▁I, ▁have, ▁the, ▁privilege, ▁of, ▁assist, ing, ▁individuals, ▁in, ▁maintain, ing, ▁excellent, ▁oral, ▁health, ., ▁One, ▁memor, able, ▁incident, ▁that, ▁stand, s, ▁out, ▁in, ▁my, ▁career, ▁occur, red, ▁during, ▁a, ▁routine, ▁check, up, ., ▁I, ▁noticed, ▁an, ▁ab, normal, ity, ▁in, ▁a, ▁patient, ', s, ▁X, -, ray, ., ▁U, pon, ▁close, r, ▁examina, tion, ,, ▁I, ▁discovered, ▁a, ▁small, ▁cavi, ty, ▁form, ing, ▁between, ▁two, ▁mo, lar, s, ., ▁The, ▁patient, ▁had, ▁not, ▁experienced, ▁any, ▁pain, ▁or, ▁, sensitiv, ity, ,, ▁so, ▁they, ...]
Name: tokens, dtype: object

In [15]:
import pandas as pd
import re
import spacy
from transformers import AutoTokenizer

# Load tokenizer and spaCy model
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
nlp = spacy.load("en_core_web_sm")

# Load dataset
df = pd.read_csv("pii_dataset.csv")

# Regex patterns
email_pattern = r'\b[\w\.-]+@[\w\.-]+\.\w+\b'
phone_pattern = r'\b(?:\+?\d{1,3}[-.\s]?)?(?:\d[-.\s]?){8,14}\d\b'
address_pattern = [
    r'\b\d{1,4}[\s\-]?(?:[A-Z][a-z]*[\s\-]?)*(?:Street|St\.|Road|Rd\.|Avenue|Ave\.|Lane|Ln\.?|Block|Sector|Nagar|Colony|Vihar|Marg|Enclave|Circle)\b.*?(?=[.,;]|$)',
    r'\b(?:House\s*No\.?|Flat\s*No\.?)\s*\d+[A-Z]?\b.*?(?=[.,;]|$)',
    r'\b(?:Near|Behind|Opposite|Beside|In front of|Adjacent to)\s+[A-Z][a-zA-Z\s&.\-]+\b'
]


name_pattern = [
    r'\bMy name is ([A-Z][a-z]+(?: [A-Z][a-z]+)*)',
    r'\bMy name is ([A-Z]{1,3}(?: [A-Z][a-z]+)+)',
    r'\bI am ([A-Z][a-z]+(?: [A-Z][a-z]+)*)',
    r'\bI am ([A-Z]{1,3}(?: [A-Z][a-z]+)+)',
    r'\bThis is ([A-Z][a-z]+(?: [A-Z][a-z]+)*)',
    r'\bThis is ([A-Z]{1,3}(?: [A-Z][a-z]+)+)'
]


# Detect pii intexes
def detect_pii_indexes(text):
    indexes = []

    # Email
    for match in re.finditer(email_pattern, text):
        indexes.append((match.start(), match.end(), 'EMAIL'))

    # Phone
    for match in re.finditer(phone_pattern, text):
        indexes.append((match.start(), match.end(), 'PHONE'))

    # Address
    for pattern in address_pattern:
      for match in re.finditer(pattern, text):
        indexes.append((match.start(), match.end(), 'ADDRESS'))


    # spaCy Names
    doc = nlp(text)
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            indexes.append((ent.start_char, ent.end_char, 'NAME'))

    # Regex Names
    for pattern in name_pattern:
        for match in re.finditer(pattern, text):
            name_text = match.group(1)
            start = match.start(1)
            end = match.end(1)
            indexes.append((start, end, 'NAME'))

    return indexes

# Label tokens
def label_tokens(text):
    indexes = detect_pii_indexes(text)
    encoding = tokenizer(text, return_offsets_mapping=True, return_tensors='pt', truncation=True)
    tokens = tokenizer.tokenize(text)
    offsets = encoding['offset_mapping'][0].tolist()
    labels = ['O'] * (len(offsets)-1)

    for index_start, index_end, entity in indexes:
        began = False
        for i, (tok_start, tok_end) in enumerate(offsets):
            if tok_end == 0:  # for start and end of sentence necessary for model
                continue
            if tok_start >= index_end:
                break
            if tok_start >= index_start and tok_end <= index_end:
                if not began:
                    labels[i-1] = f'B-{entity}'
                    began = True
                else:
                    labels[i-1] = f'I-{entity}'
    return tokens, labels

# Applying to DataFrame
token_label_data = []
for text in df['text']:
    tokens, labels = label_tokens(str(text))
    token_label_data.append({'tokens': tokens, 'labels': labels})

# Output to csv
df_labels = pd.DataFrame(token_label_data)
df_labels.to_csv("token_labels_fixed.csv", index=False)

print("Saved as token_labels_fixed.csv")

Token indices sequence length is longer than the specified maximum sequence length for this model (521 > 512). Running this sequence through the model will result in indexing errors

Saved as token_labels_fixed.csv